# my h & g keys are broken so I put them here
SCENE_WIDTH = 1200
SCENE_HEIGHT = 600

PLAYER_HEALTH = 100
PLAYER_DAMAGE = 10
PLAYER_SPEED = 5
PLAYER_JUMP = -5
PLAYER_GRAVITY = 0.5

PROJECTILE_SPEED = 10
PROJECTILE_DAMAGE = 100
PROJECTILE_LIFETIME = 500  # in milliseconds

NPC_HEALTH = 100
NPC_DAMAGE = 10
NPC_SPEED = 1
NPC_JUMP = 10
NPC_GRAVITY = 0.5

GLOBAL_GRAVITY = 0.25


CAPTION = "Welcome to pixelhalla"
FPS = 60


# config.SCENE_WIDTH/2, config.SCENE_HEIGHT/3 let it be here 



