# my h & g keys are broken so I put them here
SCENE_WIDTH = 1200
SCENE_HEIGHT = 600

PLAYER_HEALTH = 100
PLAYER_DAMAGE = 10
PLAYER_SPEED = 3
PLAYER_JUMP = -5
PLAYER_GRAVITY = 0.5
PLAYER_BAR_HEIGHT = 10
PLAYER_BAR_BACKGROUND_COLOR = (100, 100, 100)
PLAYER_BAR_HEALTH_COLOR = (255, 0, 0)

PROJECTILE_SPEED = 5
PROJECTILE_DAMAGE = 20
PROJECTILE_LIFETIME = 500  # in milliseconds

NPC_HEALTH = 100
NPC_DAMAGE = 10
NPC_SPEED = 1
NPC_JUMP = 10
NPC_GRAVITY = 0.5

GLOBAL_GRAVITY = 0.25


CAPTION = "Welcome to pixelhalla"
FPS = 60

PULSE_TIME = 0  # Track time for pulse effect
PULSE_SPEED = 0.05  # Speed of pulse animation
PULSE_SCALE = 10  # Max scale change in pixels

# Variable to debounce mouse clicks
CLICK_COOLDOWN = 200  # 200ms cooldown between clicks

GAME_STATE_LOADING = 1
GAME_STATE_PLAYING = 0
GAME_STATE_MODE_SELECT = 2
GAME_STATE_MAP_SELECT = 3
GAME_STATE_FIGHTER_SELECT = 4

# config.SCENE_WIDTH/2, config.SCENE_HEIGHT/3 let it be here 


